import Config

# Load environment variables from .env file in development
try do
  Dotenv.load!()
rescue
  # Don't fail if .env doesn't exist
  _ -> :ok
end

config :mobilizon, Mobilizon.Web.Endpoint,
  http: [
    port: String.to_integer(System.get_env("MOBILIZON_INSTANCE_HOST_PORT", "4000"))
  ],
  url: [
    host: System.get_env("MOBILIZON_INSTANCE_HOST", "localhost"),
    port: String.to_integer(System.get_env("MOBILIZON_INSTANCE_HOST_PORT", "4000")),
    scheme: System.get_env("MOBILIZON_INSTANCE_SCHEME", "http")
  ],
  secret_key_base: System.get_env("MOBILIZON_INSTANCE_SECRET_KEY_BASE", "changethis"),
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/.bin/vite",
      "--host",
      "0.0.0.0",
      "--port",
      "5173"
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :mobilizon, Mobilizon.Web.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/web/(live|views)/.*(ex)$},
      ~r{lib/web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "$metadata[$level] $message\n", level: :debug

config :mobilizon, Mobilizon.Service.Geospatial, service: Mobilizon.Service.Geospatial.Nominatim

config :mobilizon, Mobilizon.Web.Gettext, allowed_locales: ["fr", "en", "ru", "ar"]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Use SMTP when MOBILIZON_SMTP_SERVER is configured (Docker), otherwise use Local adapter
if System.get_env("MOBILIZON_SMTP_SERVER") do
  config :mobilizon, Mobilizon.Web.Email.Mailer,
    adapter: Swoosh.Adapters.SMTP,
    relay: System.get_env("MOBILIZON_SMTP_SERVER", "localhost"),
    port: String.to_integer(System.get_env("MOBILIZON_SMTP_PORT", "25")),
    username: System.get_env("MOBILIZON_SMTP_USERNAME", "test"),
    password: System.get_env("MOBILIZON_SMTP_PASSWORD", "test"),
    tls: System.get_env("MOBILIZON_SMTP_TLS", "if_available"),
    auth: System.get_env("MOBILIZON_SMTP_AUTH", "if_available"),
    ssl: System.get_env("MOBILIZON_SMTP_SSL", "false"),
    tls_options: [
      verify: :verify_none,
      versions: [:"tlsv1.2"],
      ciphers: :ssl.cipher_suites(:default, :"tlsv1.2")
    ],
    retries: 1,
    no_mx_lookups: false
else
  config :mobilizon, Mobilizon.Web.Email.Mailer, adapter: Swoosh.Adapters.Local
end

# Configure your database
config :mobilizon, Mobilizon.Storage.Repo,
  username: System.get_env("MOBILIZON_DATABASE_USERNAME", "mobilizon"),
  password: System.get_env("MOBILIZON_DATABASE_PASSWORD", "mobilizon"),
  database: System.get_env("MOBILIZON_DATABASE_DBNAME", "mobilizon_dev"),
  hostname: System.get_env("MOBILIZON_DATABASE_HOST", "localhost"),
  port: System.get_env("MOBILIZON_DATABASE_PORT", "5432"),
  pool_size: 10,
  show_sensitive_data_on_connection_error: true,
  # Logging is handled by Ecto.DevLogger
  log: false

config :mobilizon, :instance,
  name: System.get_env("MOBILIZON_INSTANCE_NAME", "Mobilizon"),
  hostname: System.get_env("MOBILIZON_INSTANCE_HOST", "Mobilizon"),
  email_from: System.get_env("MOBILIZON_INSTANCE_EMAIL"),
  email_reply_to: System.get_env("MOBILIZON_INSTANCE_EMAIL"),
  registrations_open: System.get_env("MOBILIZON_INSTANCE_REGISTRATIONS_OPEN") == "true",
  groups: true

config :mobilizon, Mobilizon.Web.Auth.Guardian,
  secret_key: System.get_env("MOBILIZON_INSTANCE_SECRET_KEY", "changethis")

# config :mobilizon, :activitypub, sign_object_fetches: false

config :mobilizon, Mobilizon.Web.Upload.Uploader.Local, uploads: "uploads"

config :mobilizon, :exports,
  path: "uploads/exports",
  formats: [
    Mobilizon.Service.Export.Participants.CSV
  ]

config :mobilizon, Mobilizon.Service.SiteMap,
  path: System.get_env("MOBILIZON_SITEMAP_PATH", "priv/static")

config :tz_world, data_dir: "_build/dev/lib/tz_world/priv"

config :mobilizon, :anonymous,
  reports: [
    allowed: true
  ]

config :unplug, :init_mode, :runtime

config :mobilizon, :restrictions,
  only_admin_can_create_groups:
    System.get_env("MOBILIZON_RESTRICTIONS_ONLY_ADMIN_CAN_CREATE_GROUPS", "false") == "true",
  only_groups_can_create_events:
    System.get_env("MOBILIZON_RESTRICTIONS_ONLY_GROUPS_CAN_CREATE_EVENTS", "false") == "true",
  allow_moderator_activity_for_pending_groups:
    System.get_env(
      "MOBILIZON_RESTRICTIONS_ALLOW_MODERATOR_ACTIVITY_FOR_PENDING_GROUPS",
      "true"
    ) == "true"

# OAuth Configuration for development

config :ueberauth,
       Ueberauth,
       providers: [
         # LinkedIn now uses direct OAuth2 implementation for better reliability
         # linkedin: {Ueberauth.Strategy.LinkedIn, []}
         # Add other providers here as needed for development
       ]

config :mobilizon, :auth,
  oauth_consumer_strategies: [
    # Still supported via direct OAuth2 implementation
    :linkedin
  ]

# Direct LinkedIn OAuth2 configuration (replaces Ueberauth LinkedIn)
config :mobilizon, :linkedin,
  client_id: System.get_env("LINKEDIN_CLIENT_ID", "77es95oq72tify"),
  client_secret: System.get_env("LINKEDIN_CLIENT_SECRET", "WPL_AP1.okqW0Aw0MhW01D28.KX0ypw=="),
  redirect_uri:
    System.get_env("LINKEDIN_REDIRECT_URI", "http://localhost:4000/auth/linkedin/callback")

# ── Survey Plugin (dev + Docker) ──────────────────────────────────────────────
# Mirrors the survey config from docker.exs but without Mobilizon.Service.Config.Helpers
# (that module isn't available at config compile time in dev mode).
surveys_enabled_dev =
  System.get_env("MOBILIZON_PLUGIN_SURVEYS_ENABLED", "false") == "true"

config :mobilizon, Mobilizon.Service.Plugins.Surveys,
  enabled: surveys_enabled_dev,
  adapter:
    if(surveys_enabled_dev,
      do: Mobilizon.Service.Plugins.Surveys.ExternalAdapter,
      else: Mobilizon.Service.Plugins.Surveys.NoopAdapter
    ),
  adapter_url: System.get_env("MOBILIZON_PLUGIN_SURVEYS_ADAPTER_URL", ""),
  adapter_static_url: System.get_env("MOBILIZON_PLUGIN_SURVEYS_ADAPTER_STATIC_URL", ""),
  api_key: System.get_env("MOBILIZON_PLUGIN_SURVEYS_API_KEY", "")

# ── Front-end analytics from .env (dev / Docker dev via mix phx.server) ───────
# docker.exs is only used as runtime.exs in the production image; without this
# block, :analytics providers stay empty and GraphQL never exposes GA/GTM.
google_analytics_enabled_dev =
  System.get_env("MOBILIZON_FRONT_END_ANALYTICS_GOOGLE_ENABLED", "false") == "true"

google_analytics_measurement_id_dev =
  System.get_env("MOBILIZON_FRONT_END_ANALYTICS_GOOGLE_MEASUREMENT_ID", nil)

google_analytics_anonymize_ip_dev =
  System.get_env("MOBILIZON_FRONT_END_ANALYTICS_GOOGLE_ANONYMIZE_IP", "true") == "true"

google_tag_manager_enabled_dev =
  System.get_env("MOBILIZON_GOOGLE_TAG_MANAGER_ENABLED", "false") == "true"

google_tag_manager_container_id_dev =
  System.get_env("MOBILIZON_GOOGLE_TAG_MANAGER_CONTAINER_ID", nil)
  |> case do
    id when is_binary(id) and id != "" -> id
    _ -> nil
  end

analytics_providers_dev = []

analytics_providers_dev =
  if google_analytics_enabled_dev and google_analytics_measurement_id_dev do
    analytics_providers_dev ++ [Mobilizon.Service.FrontEndAnalytics.GoogleAnalytics]
  else
    analytics_providers_dev
  end

analytics_providers_dev =
  if google_tag_manager_enabled_dev and google_tag_manager_container_id_dev do
    analytics_providers_dev ++ [Mobilizon.Service.FrontEndAnalytics.GoogleTagManager]
  else
    analytics_providers_dev
  end

config :mobilizon, :analytics, providers: analytics_providers_dev

config :mobilizon, Mobilizon.Service.FrontEndAnalytics.GoogleAnalytics,
  enabled: google_analytics_enabled_dev,
  measurementId: google_analytics_measurement_id_dev,
  anonymizeIp: google_analytics_anonymize_ip_dev,
  sendPageView: true,
  csp: [
    connect_src: ["www.google-analytics.com", "www.googletagmanager.com"],
    script_src: ["www.googletagmanager.com"],
    img_src: ["www.google-analytics.com"]
  ]

config :mobilizon, Mobilizon.Service.FrontEndAnalytics.GoogleTagManager,
  enabled: google_tag_manager_enabled_dev,
  containerId: google_tag_manager_container_id_dev,
  csp: [
    connect_src: ["www.google-analytics.com", "www.googletagmanager.com"],
    script_src: ["www.googletagmanager.com"],
    img_src: ["www.google-analytics.com", "www.googletagmanager.com"],
    frame_src: ["www.googletagmanager.com"]
  ]

active_campaign_list_id_dev =
  case Integer.parse(System.get_env("MOBILIZON_ACTIVE_CAMPAIGN_LIST_ID", "7")) do
    {n, _} -> n
    :error -> 7
  end

active_campaign_api_url_dev =
  case System.get_env("MOBILIZON_ACTIVE_CAMPAIGN_API_URL") do
    url when is_binary(url) and url != "" -> url |> String.trim() |> String.trim_trailing("/")
    _ -> nil
  end

active_campaign_api_key_dev =
  case System.get_env("MOBILIZON_ACTIVE_CAMPAIGN_API_KEY") do
    k when is_binary(k) and k != "" -> k
    _ -> nil
  end

config :mobilizon, Mobilizon.Service.ActiveCampaign,
  enabled: System.get_env("MOBILIZON_ACTIVE_CAMPAIGN_ENABLED", "false") == "true",
  api_url: active_campaign_api_url_dev,
  api_key: active_campaign_api_key_dev,
  list_id: active_campaign_list_id_dev

# HTTP client configuration for OAuth requests
config :oauth2, :http_client, HTTPoison

# HTTPoison configuration with better timeout handling
config :httpoison,
  timeout: 30_000,
  recv_timeout: 30_000,
  hackney: [
    timeout: 30_000,
    recv_timeout: 30_000,
    pool_timeout: 10_000,
    max_connections: 50,
    # Additional reliability options
    retry: 3,
    retry_delay: 1000,
    follow_redirect: true,
    max_redirect: 3,
    # Connection pool options
    pool: :oauth_pool
  ]
